//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextCanvas.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultObjectNamesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultObjectNamesResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NextCanvas.Properties.DefaultObjectNamesResources", typeof(DefaultObjectNamesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text box.
        /// </summary>
        public static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brushes.
        /// </summary>
        public static string ToolGroups_Brushes {
            get {
                return ResourceManager.GetString("ToolGroups_Brushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erasers.
        /// </summary>
        public static string ToolGroups_Erasers {
            get {
                return ResourceManager.GetString("ToolGroups_Erasers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Highlighters.
        /// </summary>
        public static string ToolGroups_Highlighters {
            get {
                return ResourceManager.GetString("ToolGroups_Highlighters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shapes.
        /// </summary>
        public static string ToolGroups_Shapes {
            get {
                return ResourceManager.GetString("ToolGroups_Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Big brush.
        /// </summary>
        public static string Tools_BigBrush {
            get {
                return ResourceManager.GetString("Tools_BigBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Big eraser.
        /// </summary>
        public static string Tools_BigEraser {
            get {
                return ResourceManager.GetString("Tools_BigEraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Highlighter.
        /// </summary>
        public static string Tools_Highlighter {
            get {
                return ResourceManager.GetString("Tools_Highlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Huge eraser.
        /// </summary>
        public static string Tools_HugeEraser {
            get {
                return ResourceManager.GetString("Tools_HugeEraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Medium brush.
        /// </summary>
        public static string Tools_MediumBrush {
            get {
                return ResourceManager.GetString("Tools_MediumBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Medium eraser.
        /// </summary>
        public static string Tools_MediumEraser {
            get {
                return ResourceManager.GetString("Tools_MediumEraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rectangle.
        /// </summary>
        public static string Tools_Rectangle {
            get {
                return ResourceManager.GetString("Tools_Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Small eraser.
        /// </summary>
        public static string Tools_SmallEraser {
            get {
                return ResourceManager.GetString("Tools_SmallEraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thin brush.
        /// </summary>
        public static string Tools_ThinBrush {
            get {
                return ResourceManager.GetString("Tools_ThinBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web browser.
        /// </summary>
        public static string WebBrowser {
            get {
                return ResourceManager.GetString("WebBrowser", resourceCulture);
            }
        }
    }
}
